project_name: suma

# rvm_io configs
rvm1_rubies:
  - ruby-2.5.1
rvm1_user: 'vagrant'
ruby_version: ruby-2.5.1

# MySQL configs (geerlinguy.mysql)
mysql_root_password: 'mysqlrootpassword'
mysql_bind_address: '0.0.0.0'
mysql_enabled_on_startup: yes

mysql_databases:
  - name: suma
    encoding: utf8
mysql_users:
  - name: suma
    host: 'localhost'
    password: 12345
    priv: 'suma.*:ALL'

# Apache configs (geerlingguy.apache)
apache_vhosts_filename: "{{ project_name }}.conf"
apache_allow_override: "All"
apache_options: "+Indexes +FollowSymLinks +Includes"
apache_vhosts:
  - servername: "localhost"
    documentroot: "/var/www/html"
    extra_parameters: |
      <Directory "/var/www/html/sumaserver/">
          RewriteEngine On
          RewriteCond %{REQUEST_FILENAME} -s [OR]
          RewriteCond %{REQUEST_FILENAME} -l [OR]
          RewriteCond %{REQUEST_FILENAME} -d
          RewriteRule ^.*$ - [NC,L]
          RewriteRule ^.*$ index.php [NC,L]
        </Directory>

# PHP configs (geerlinguy.php)
php_enablerepo: remi
php_version: "7.1"
php_memory_limit: "128M"
php_max_execution_time: "90"
php_upload_max_filesize: "256M"
php_date_timezone: "America/New_York"
php_enable_apc: false
php_opcache_enable: "0"
php_packages:
  - php
  - php-cli
  - php-common
  - php-devel
  - php-pdo
  - php-mbstring
  - php-mcrypt
  - php-mysql
  - php-xml
  - php-curl
